bugfix/update-lifecycle-policy
craft-machine/terraform-aws-base-ecs-service pull request #1
Opened 2023-01-06 15:34 UTC by tbaledent

When lifecycle create_before_destroy is set to true it ends up creating an error if your terraform deploy needs to replace the ecs service since ecs services have to be idempotent, as seen here in the error I got in lab1-service qa environment
[https://app.circleci.com/pipelines/github/craft-machine/lab1-service/315/workflows/b56fd6eb-414b-4478-bd29-68770eda9922/jobs/2292?invite=true#s[…]59](https://app.circleci.com/pipelines/github/craft-machine/lab1-service/315/workflows/b56fd6eb-414b-4478-bd29-68770eda9922/jobs/2292?invite=true#step-104-59)

2023-01-23 07:38 UTC, adys requested changes

2023-01-23 07:38 UTC, adys commented on main.tf
> +    create_before_destroy = false
@tbaledent do we need to keep the lifecycle block in place since "false" is the default? I'd suggest we remove the whole lifecycle block.

2023-01-23 16:32 UTC, tbaledent commented on main.tf
> +    create_before_destroy = false
not really, was just a personal preference since a lot of times i'd rather be explicit rather than implicit with `create_before_destroy` especially if it was set to true previously

2023-01-25 10:15 UTC, adys commented on main.tf
> +    create_before_destroy = false
@tbaledent okay we can keep it explicit

2023-01-25 10:16 UTC, adys approved these changes

2023-01-27 21:30 UTC, merged