cpu and memory variables introduced
craft-machine/terraform-aws-base-ecs-service pull request #4
Opened 2023-02-27 14:40 UTC by yauheni-sem

2023-02-27 14:58 UTC, YAndrew91 commented on variables.tf
> +  default     = 0
@adys @yauheni-sem i am not sure if zero value is handled in the same way as no value

2023-02-27 15:08 UTC, yauheni-sem commented on variables.tf
> +  default     = 0
Hm, the 0 value should be equivalent to unset: https://github.com/hashicorp/terraform-provider-aws/blob/834839aec8a8b62896bcd291a3cee547885f2993/internal/service/ecs/task_definition_equivalency.go#L64

2023-02-27 15:48 UTC, YAndrew91 approved these changes

2023-02-28 09:11 UTC, adys requested changes

2023-02-28 09:11 UTC, adys commented on variables.tf
> +  default     = 0
@yauheni-sem you shared a reference to the part where container definition is set. [Here is the cpu set](https://github.com/hashicorp/terraform-provider-aws/blob/834839aec8a8b62896bcd291a3cee547885f2993/internal/service/ecs/task_definition.go#L84) on the Task level. 

Additionally, I've tested it. (btw, feel free to use [dummy-service](https://github.com/craft-machine/dummy-service) for such tests). Just run terraform locally and play around.

Long story short, let's set the default to **null** instead of 0.

2023-02-28 09:18 UTC, yauheni-sem commented on variables.tf
> +  default     = 0
Thanks for the check and suggestion! I've updated the default values to `null`

2023-02-28 09:20 UTC, adys approved these changes

2023-02-28 09:21 UTC, merged